// <auto-generated>
// This file was generated by a tool; any manual changes may be lost.
// </auto-generated>

namespace FtrackDotNet.Models;

using System.Text.Json;
#pragma warning disable CS8669
public partial record ReviewSessionFolder {
	public string Name { get; set; } = null!;
	public string? ProjectId { get; set; }
	public string Id { get; init; } = null!;
	public ReviewSession[]? ReviewSessions { get; set; }
}
public partial record AssetVersionStatusChange : StatusChange {
}
public partial record User : BaseUser {
	public string Username { get; set; } = null!;
	public bool IsActive { get; set; }
	public bool? RequireDetailsUpdate { get; set; }
	public bool? IsOtpEnabled { get; set; }
	public bool? IsTotpEnabled { get; set; }
	public Timelog[]? Timelogs { get; set; }
	public UserTaskTypeLink[]? TaskTypeLinks { get; set; }
	public Membership[]? Memberships { get; set; }
	public Metadata[]? Metadata { get; set; }
	public UserSecurityRole[]? UserSecurityRoles { get; set; }
	public string? UserTypeId { get; set; }
	public UserCustomAttributeValue[]? CustomAttributes { get; set; }
	public CustomAttributeLink[]? CustomAttributeLinks { get; set; }
	public CustomAttributeLinkFrom[]? CustomAttributeLinksFrom { get; set; }
}
public partial record ReviewSessionInvitee {
	public string Email { get; set; } = null!;
	public string Name { get; set; } = null!;
	public string? LastSentAt { get; set; }
	public string ReviewSessionId { get; set; } = null!;
	public string Id { get; init; } = null!;
	public string CreatedById { get; set; } = null!;
	public string CreatedAt { get; set; } = null!;
	public bool? CreatedFromSharedUrl { get; set; }
	public ReviewSessionObjectStatus[]? Statuses { get; set; }
	public string? ResourceId { get; set; }
}
public partial record ApiKey {
	public string Id { get; init; } = null!;
	public string? Identifier { get; set; }
	public string? ResourceId { get; set; }
	public string? Prefix { get; set; }
	public string? Description { get; set; }
	public bool? Enabled { get; set; }
	public string? LastUsed { get; set; }
	public string? CreatedAt { get; set; }
	public SecurityRole[]? Roles { get; set; }
	public Project[]? Projects { get; set; }
}
public partial record ReviewSessionObjectAnnotation {
	public string? ReviewSessionObjectId { get; set; }
	public string Id { get; init; } = null!;
	public string? Data { get; set; }
	public int FrameNumber { get; set; }
	public string CreatedAt { get; set; } = null!;
	public string? UpdatedAt { get; set; }
}
public partial record CustomAttributeLinkFrom {
	public string? Id { get; init; }
	public string FromId { get; set; } = null!;
	public string? FromEntityType { get; set; }
	public string ToId { get; set; } = null!;
	public string? ToEntityType { get; set; }
	public string ConfigurationId { get; set; } = null!;
}
public partial record ComponentLocation {
	public string? ComponentId { get; set; }
	public string? LocationId { get; set; }
	public string? ResourceIdentifier { get; set; }
	public object? Url { get; set; }
	public string Id { get; init; } = null!;
}
public partial record Project : Context {
	public string? FullName { get; set; }
	public string? Root { get; set; }
	public string? StartDate { get; set; }
	public string? EndDate { get; set; }
	public bool IsGlobal { get; set; }
	public bool? IsPrivate { get; set; }
	public string ProjectSchemaId { get; set; } = null!;
	public string Status { get; set; } = null!;
	public string? Color { get; set; }
	public TypedContext[]? Descendants { get; set; }
	public Metadata[]? Metadata { get; set; }
	public ReviewSession[]? ReviewSessions { get; set; }
	public string? DiskId { get; set; }
	public ReviewSessionFolder[]? ReviewSessionFolders { get; set; }
	public CalendarEvent[]? CalendarEvents { get; set; }
	public UserSecurityRoleProject[]? UserSecurityRoleProjects { get; set; }
}
public partial record TypedContext : Context, IFtrackEntity
{
	public double Bid { get; set; }
	public double? TimeLogged { get; set; }
	public double? BidTimeLoggedDifference { get; set; }
	public string? Description { get; set; }
	public string? StartDate { get; set; }
	public string? EndDate { get; set; }
	public string StatusId { get; set; } = null!;
	public string? ThumbnailSourceId { get; set; }
	public string TypeId { get; set; } = null!;
	public string PriorityId { get; set; } = null!;
	public string ObjectTypeId { get; set; } = null!;
	public double Sort { get; set; }
	public Metadata[]? Metadata { get; set; }
	public TypedContext[]? Ancestors { get; set; }
	public TypedContext[]? Descendants { get; set; }
	public TypedContextList[]? Lists { get; set; }
	public TypedContextLink[]? IncomingLinks { get; set; }
	public TypedContextLink[]? OutgoingLinks { get; set; }
	public StatusChange[]? StatusChanges { get; set; }
	public SplitTaskPart[]? SplitParts { get; set; }
}
public partial record Event {
	public int Id { get; init; }
	public string? ParentType { get; set; }
	public string? ParentId { get; set; }
	public string? ProjectId { get; set; }
	public string? UserId { get; set; }
	public string? Action { get; set; }
	public string? Insert { get; set; }
	public string? Data { get; set; }
	public string? CreatedAt { get; set; }
	public Feed[]? Feeds { get; set; }
}
public partial record ManagerType {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
}
public partial record Collaborator : BaseUser {
	public string? CreatedFromSharedUrl { get; set; }
}
public partial record TypedContextStatusChange : StatusChange {
}
public partial record CustomConfigurationBase {
	public string Id { get; init; } = null!;
	public string? Key { get; set; }
	public string? EntityType { get; set; }
	public string? ObjectTypeId { get; set; }
	public bool Core { get; set; }
	public string? Label { get; set; }
	public int? Sort { get; set; }
	public string? GroupId { get; set; }
	public string Config { get; set; } = null!;
	public string? ProjectId { get; set; }
	public SecurityRole[]? ReadSecurityRoles { get; set; }
	public SecurityRole[]? WriteSecurityRoles { get; set; }
}
public partial record CustomAttributeLink {
	public string? Id { get; init; }
	public string FromId { get; set; } = null!;
	public string? FromEntityType { get; set; }
	public string ToId { get; set; } = null!;
	public string? ToEntityType { get; set; }
	public string ConfigurationId { get; set; } = null!;
}
public partial record UserSession {
	public string Id { get; init; } = null!;
	public string? UserId { get; set; }
	public bool? Valid { get; set; }
	public string? AccessedTime { get; set; }
	public string? CreationTime { get; set; }
}
public partial record Priority : IFtrackEntity
{
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public double? Value { get; set; }
	public int? Sort { get; set; }
	public string? Color { get; set; }
	public Task[]? Tasks { get; set; }
	public string EntityType { get; set; }
	public FtrackPrimaryKey[] GetPrimaryKeys()
	{
		throw new NotImplementedException();
	}
}
public partial record Dashboard {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public string? CreatedById { get; set; }
	public bool? IsSharedWithEveryone { get; set; }
	public DashboardWidget[]? Widgets { get; set; }
	public DashboardResource[]? DashboardResources { get; set; }
}
public partial record ReviewSessionObjectStatus {
	public string? ReviewSessionInviteeId { get; set; }
	public string? ReviewSessionObjectId { get; set; }
	public string? Status { get; set; }
	public string Id { get; init; } = null!;
	public string CreatedAt { get; set; } = null!;
	public string? ResourceId { get; set; }
}
public partial record ObjectType : IFtrackEntity
{
	public string EntityType { get; set; }
	public FtrackPrimaryKey[] GetPrimaryKeys()
	{
		throw new NotImplementedException();
	}
	public string Id { get; init; } = null!;
	public string Name { get; set; } = null!;
	public int Sort { get; set; }
	public ProjectSchema[]? ProjectSchemas { get; set; }
	public string Icon { get; set; } = null!;
	public bool IsTimeReportable { get; set; }
	public bool IsTaskable { get; set; }
	public bool IsTypeable { get; set; }
	public bool IsStatusable { get; set; }
	public bool IsSchedulable { get; set; }
	public bool? IsLeaf { get; set; }
	public bool? IsPrioritizable { get; set; }
	public Task[]? Tasks { get; set; }
}
public partial record Status : IFtrackEntity
{
	public string EntityType { get; set; }
	public FtrackPrimaryKey[] GetPrimaryKeys()
	{
		throw new NotImplementedException();
	}
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public int? Sort { get; set; }
	public string? Color { get; set; }
	public bool IsActive { get; set; }
	public Task[]? Tasks { get; set; }
}
public partial record Setting {
	public string Name { get; init; } = null!;
	public string Group { get; init; } = null!;
	public string? Value { get; set; }
}
public partial record Appointment {
	public string Id { get; init; } = null!;
	public string Type { get; set; } = null!;
	public string ResourceId { get; set; } = null!;
	public string ContextId { get; set; } = null!;
}
public partial record AssetVersion {
	public string Id { get; init; } = null!;
	public string? ProjectId { get; set; }
	public string? AssetId { get; set; }
	public int? Version { get; set; }
	public string? ThumbnailId { get; set; }
	public object? ThumbnailUrl { get; set; }
	public string? Comment { get; set; }
	public string? Date { get; set; }
	public string? UserId { get; set; }
	public string? TaskId { get; set; }
	public bool IsPublished { get; set; }
	public bool? IsLatestVersion { get; set; }
	public string StatusId { get; set; } = null!;
	public AssetVersion[]? UsesVersions { get; set; }
	public Component[]? Components { get; set; }
	public AssetVersion[]? UsedInVersions { get; set; }
	public Metadata[]? Metadata { get; set; }
	public Note[]? Notes { get; set; }
	public ReviewSessionObject[]? ReviewSessionObjects { get; set; }
	public AssetVersionList[]? Lists { get; set; }
	public AssetVersionLink[]? IncomingLinks { get; set; }
	public AssetVersionLink[]? OutgoingLinks { get; set; }
	public string? Link { get; set; }
	public StatusChange[]? StatusChanges { get; set; }
	public AssetVersionCustomAttributeValue[]? CustomAttributes { get; set; }
	public CustomAttributeLink[]? CustomAttributeLinks { get; set; }
	public CustomAttributeLinkFrom[]? CustomAttributeLinksFrom { get; set; }
}
public partial record CalendarEvent {
	public string Name { get; set; } = null!;
	public string Start { get; set; } = null!;
	public string End { get; set; } = null!;
	public string? ProjectId { get; set; }
	public string Id { get; init; } = null!;
	public CalendarEventResource[]? CalendarEventResources { get; set; }
	public string? CreatedAt { get; set; }
	public string? CreatedById { get; set; }
	public double? Estimate { get; set; }
	public double? Effort { get; set; }
	public string? TypeId { get; set; }
	public bool? Leave { get; set; }
	public bool? Everyone { get; set; }
	public bool? Forecast { get; set; }
	public Metadata[]? Metadata { get; set; }
}
public partial record ReviewSessionObject {
	public string Name { get; set; } = null!;
	public string Description { get; set; } = null!;
	public string Version { get; set; } = null!;
	public string VersionId { get; set; } = null!;
	public string ReviewSessionId { get; set; } = null!;
	public string Id { get; init; } = null!;
	public string CreatedAt { get; set; } = null!;
	public double SortOrder { get; set; }
	public ReviewSessionObjectStatus[]? Statuses { get; set; }
	public Note[]? Notes { get; set; }
	public ReviewSessionObjectAnnotation[]? Annotations { get; set; }
}
public partial record StatusRuleGroup {
	public string Id { get; init; } = null!;
	public string EntityType { get; set; } = null!;
	public string SchemaId { get; set; } = null!;
	public string StatusId { get; set; } = null!;
	public StatusRule[]? StatusRules { get; set; }
	public string? RoleId { get; set; }
}
public partial record SplitTaskPart {
	public string Id { get; init; } = null!;
	public string? Label { get; set; }
	public string StartDate { get; set; } = null!;
	public string EndDate { get; set; } = null!;
	public string TaskId { get; set; } = null!;
}
public partial record NoteLabel {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public int? Sort { get; set; }
	public string? Color { get; set; }
}
public partial record ReviewSession {
	public string Name { get; set; } = null!;
	public string? Availability { get; set; }
	public string Description { get; set; } = null!;
	public string StartDate { get; set; } = null!;
	public string EndDate { get; set; } = null!;
	public string ProjectId { get; set; } = null!;
	public string Id { get; init; } = null!;
	public string? ReviewSessionFolderId { get; set; }
	public string CreatedById { get; set; } = null!;
	public string CreatedAt { get; set; } = null!;
	public ReviewSessionObject[]? ReviewSessionObjects { get; set; }
	public ReviewSessionInvitee[]? ReviewSessionInvitees { get; set; }
	public EntitySetting[]? Settings { get; set; }
	public bool? IsModerated { get; set; }
	public bool? PassphraseEnabled { get; set; }
	public bool? ShareableUrlEnabled { get; set; }
	public string? Passphrase { get; set; }
	public string? ThumbnailId { get; set; }
	public object? ThumbnailUrl { get; set; }
	public string? ThumbnailSourceId { get; set; }
	public bool? IsOpen { get; set; }
	public Metadata[]? Metadata { get; set; }
}
public partial record UserApplicationState {
	public string UserId { get; init; } = null!;
	public string Key { get; init; } = null!;
	public string Value { get; set; } = null!;
}
public partial record ListCategory {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public List[]? Lists { get; set; }
}
public partial record UserType {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
}
public partial record NoteAnnotationComponent : NoteComponent {
	public object? Data { get; set; }
}
public partial record Timer {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public string Comment { get; set; } = null!;
	public string Start { get; set; } = null!;
	public string? ContextId { get; set; }
	public string UserId { get; set; } = null!;
}
public partial record ContainerComponent : Component {
	public Component[]? Members { get; set; }
}
public partial record CustomAttributeType {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public string? FormConfig { get; set; }
	public bool Core { get; set; }
	public CustomAttributeConfiguration[]? CustomAttributeConfigurations { get; set; }
}
public partial record TaskTemplate : IFtrackEntity
{
	public string EntityType { get; set; }
	public FtrackPrimaryKey[] GetPrimaryKeys()
	{
		throw new NotImplementedException();
	}
	public string Id { get; init; } = null!;
	public string Name { get; set; } = null!;
	public string ProjectSchemaId { get; set; } = null!;
	public TaskTemplateItem[]? Items { get; set; }
}
public partial record ProjectSchema : IFtrackEntity
{
	public string EntityType { get; set; }
	public FtrackPrimaryKey[] GetPrimaryKeys()
	{
		throw new NotImplementedException();
	}
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public string? AssetVersionWorkflowSchemaId { get; set; }
	public string? TaskWorkflowSchemaId { get; set; }
	public string? TaskTypeSchemaId { get; set; }
	public ObjectType[]? ObjectTypes { get; set; }
	public ProjectSchemaOverride[]? TaskWorkflowSchemaOverrides { get; set; }
	public Schema[]? ObjectTypeSchemas { get; set; }
	public TaskTemplate[]? TaskTemplates { get; set; }
}
public partial record CalendarEventResource {
	public string CalendarEventId { get; set; } = null!;
	public string ResourceId { get; set; } = null!;
	public string Id { get; init; } = null!;
	public string? CreatedAt { get; set; }
	public string? CreatedById { get; set; }
}
public partial record Component {
	public string SystemType { get; set; } = null!;
	public string Name { get; set; } = null!;
	public int? Size { get; set; }
	public string? FileType { get; set; }
	public string? ContainerId { get; set; }
	public string? VersionId { get; set; }
	public string Id { get; init; } = null!;
	public ComponentLocation[]? ComponentLocations { get; set; }
	public Metadata[]? Metadata { get; set; }
	public string? ProjectId { get; set; }
	public CustomAttributeLink[]? CustomAttributeLinks { get; set; }
	public CustomAttributeLinkFrom[]? CustomAttributeLinksFrom { get; set; }
}
public partial record Feed {
	public string Id { get; init; } = null!;
	public string? OwnerId { get; set; }
	public int? SocialId { get; set; }
	public int? Distance { get; set; }
	public string? Relation { get; set; }
	public string? CreatedAt { get; set; }
	public string? ClusterId { get; set; }
}
public partial record ActionLog {
	public int? Id { get; init; }
	public string? Message { get; set; }
	public string? Status { get; set; }
	public string ActionId { get; set; } = null!;
	public string? CreatedAt { get; set; }
}
public partial record DashboardWidget {
	public string Id { get; init; } = null!;
	public string? Type { get; set; }
	public string? DashboardId { get; set; }
	public string? Config { get; set; }
	public double? Sort { get; set; }
}
public partial record Resource {
	public string ResourceType { get; set; } = null!;
	public string Id { get; init; } = null!;
	public Appointment[]? Appointments { get; set; }
	public Appointment[]? Assignments { get; set; }
	public Appointment[]? Allocations { get; set; }
	public DashboardResource[]? DashboardResources { get; set; }
}
public partial record NoteCategory : NoteLabel {
}
public partial record NoteComponent {
	public string ComponentId { get; init; } = null!;
	public string NoteId { get; init; } = null!;
	public object? Url { get; set; }
	public object? ThumbnailUrl { get; set; }
}
public partial record DashboardResource {
	public string DashboardId { get; init; } = null!;
	public string ResourceId { get; init; } = null!;
}
public partial record Context : IFtrackEntity
{
	public string EntityType { get; set; }
	public FtrackPrimaryKey[] GetPrimaryKeys()
	{
		throw new NotImplementedException();
	}
	public string ContextType { get; set; } = null!;
	public string Id { get; init; } = null!;
	public string Name { get; set; } = null!;
	public string? ParentId { get; set; }
	public string? ThumbnailId { get; set; }
	public object? ThumbnailUrl { get; set; }
	public Context[]? Children { get; set; }
	public Appointment[]? Appointments { get; set; }
	public Appointment[]? Assignments { get; set; }
	public Appointment[]? Allocations { get; set; }
	public Asset[]? Assets { get; set; }
	public Timelog[]? Timelogs { get; set; }
	public Scope[]? Scopes { get; set; }
	public Note[]? Notes { get; set; }
	public string? Link { get; set; }
	public Manager[]? Managers { get; set; }
	public string? CreatedById { get; set; }
	public string? CreatedAt { get; set; }
	public string? ProjectId { get; set; }
	public ContextCustomAttributeValue[]? CustomAttributes { get; set; }
	public CustomAttributeLink[]? CustomAttributeLinks { get; set; }
	public CustomAttributeLinkFrom[]? CustomAttributeLinksFrom { get; set; }
}
public partial record Membership {
	public string Id { get; init; } = null!;
	public string GroupId { get; set; } = null!;
	public string UserId { get; set; } = null!;
}
public partial record WorkflowSchema {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public Status[]? Statuses { get; set; }
	public ProjectSchemaOverride[]? Overrides { get; set; }
}
public partial record StatusRule {
	public string Id { get; init; } = null!;
	public string StatusRuleGroupId { get; set; } = null!;
	public string StatusId { get; set; } = null!;
}
public partial record TypedContextStatusRuleGroup : StatusRuleGroup {
	public string ObjectTypeId { get; set; } = null!;
}
public partial record BaseUser : Resource {
	public string? FirstName { get; set; }
	public string? LastName { get; set; }
	public string? Email { get; set; }
	public string? ThumbnailId { get; set; }
	public object? ThumbnailUrl { get; set; }
}
public partial record Type : IFtrackEntity
{
	public string EntityType { get; set; }
	public FtrackPrimaryKey[] GetPrimaryKeys()
	{
		throw new NotImplementedException();
	}
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public string Color { get; set; } = null!;
	public int Sort { get; set; }
	public bool IsBillable { get; set; }
	public TaskTypeSchema[]? TaskTypeSchemas { get; set; }
	public Task[]? Tasks { get; set; }
}
public partial record JobComponent {
	public string ComponentId { get; init; } = null!;
	public string JobId { get; init; } = null!;
	public object? Url { get; set; }
}
public partial record Trigger {
	public string Id { get; init; } = null!;
	public string Filter { get; set; } = null!;
	public string? AutomationId { get; set; }
}
public partial record SequenceComponent : ContainerComponent {
	public int Padding { get; set; }
}
public partial record UserSecurityRoleProject {
	public string Id { get; init; } = null!;
	public string? UserSecurityRoleId { get; set; }
	public string? ProjectId { get; set; }
}
public partial record SettingComponent {
	public string ComponentId { get; init; } = null!;
	public string Name { get; init; } = null!;
	public string Group { get; init; } = null!;
	public object? Url { get; set; }
	public object? ThumbnailUrl { get; set; }
}
public partial record Manager {
	public string Id { get; init; } = null!;
	public string? ContextId { get; set; }
	public string? TypeId { get; set; }
	public string? UserId { get; set; }
}
public partial record WebhookAction : Action {
	public string WebhookUrl { get; set; } = null!;
	public string? Headers { get; set; }
}
public partial record WorkflowSchemaStatus {
	public string WorkflowSchemaId { get; init; } = null!;
	public string StatusId { get; init; } = null!;
}
public partial record CustomAttributeValue {
	public string ConfigurationId { get; init; } = null!;
	public JsonElement? Value { get; set; }
	public string EntityId { get; init; } = null!;
}
public partial record AssetVersionList : List {
	public AssetVersion[]? Items { get; set; }
}
public partial record TaskTemplateItem {
	public string Id { get; init; } = null!;
	public string TemplateId { get; set; } = null!;
	public string TaskTypeId { get; set; } = null!;
}
public partial record SchemaType {
	public string TypeId { get; init; } = null!;
	public string SchemaId { get; init; } = null!;
	public int? Sort { get; set; }
}
public partial record SchemaStatus {
	public string StatusId { get; init; } = null!;
	public string SchemaId { get; init; } = null!;
	public int? Sort { get; set; }
}
public partial record NoteLabelLink {
	public string NoteId { get; init; } = null!;
	public string LabelId { get; init; } = null!;
}
public partial record TaskTypeSchema : IFtrackEntity
{
	public string EntityType { get; set; }
	public FtrackPrimaryKey[] GetPrimaryKeys()
	{
		throw new NotImplementedException();
	}
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public Type[]? Types { get; set; }
}
public partial record Timelog {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public string Comment { get; set; } = null!;
	public string Start { get; set; } = null!;
	public double Duration { get; set; }
	public double? TimeZoneOffset { get; set; }
	public string? UserId { get; set; }
	public string? ContextId { get; set; }
}
public partial record AssetVersionLink {
	public string Id { get; init; } = null!;
	public string FromId { get; set; } = null!;
	public string ToId { get; set; } = null!;
	public Metadata[]? Metadata { get; set; }
}
public partial record SecurityRole {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public string? Type { get; set; }
	public UserSecurityRole[]? UserSecurityRoles { get; set; }
}
public partial record ListObject {
	public string Id { get; init; } = null!;
	public string EntityId { get; set; } = null!;
	public string ListId { get; set; } = null!;
	public ListObjectCustomAttributeValue[]? CustomAttributes { get; set; }
}
public partial record ReviewSessionObjectAnnotationComponent {
	public string ComponentId { get; init; } = null!;
	public string FrameNumber { get; set; } = null!;
	public string ReviewSessionObjectId { get; init; } = null!;
	public object? Url { get; set; }
	public object? ThumbnailUrl { get; set; }
}
public partial record TypedContextList : List {
	public Task[]? Items { get; set; }
}
public partial record ProjectSchemaOverride {
	public string Id { get; init; } = null!;
	public string? ProjectSchemaId { get; set; }
	public string? WorkflowSchemaId { get; set; }
	public string? TypeId { get; set; }
}
public partial record Job {
	public string Id { get; init; } = null!;
	public string Status { get; set; } = null!;
	public string? UserId { get; set; }
	public string? Data { get; set; }
	public string Type { get; set; } = null!;
	public string? CreatedAt { get; set; }
	public string? FinishedAt { get; set; }
	public JobComponent[]? JobComponents { get; set; }
}
public partial record UserSecurityRole {
	public string Id { get; init; } = null!;
	public string? UserId { get; set; }
	public string? SecurityRoleId { get; set; }
	public bool? IsAllProjects { get; set; }
	public bool? IsAllOpenProjects { get; set; }
	public UserSecurityRoleProject[]? UserSecurityRoleProjects { get; set; }
}
public partial record Asset {
	public string Id { get; init; } = null!;
	public string? ProjectId { get; set; }
	public string? Name { get; set; }
	public string? ContextId { get; set; }
	public string? TypeId { get; set; }
	public AssetVersion[]? Versions { get; set; }
	public Metadata[]? Metadata { get; set; }
	public TypedContext[]? Ancestors { get; set; }
	public AssetCustomAttributeValue[]? CustomAttributes { get; set; }
	public CustomAttributeLink[]? CustomAttributeLinks { get; set; }
	public CustomAttributeLinkFrom[]? CustomAttributeLinksFrom { get; set; }
}
public partial record TypedContextLink {
	public string Id { get; init; } = null!;
	public string FromId { get; set; } = null!;
	public string ToId { get; set; } = null!;
	public double? Lag { get; set; }
	public string? Type { get; set; }
	public Metadata[]? Metadata { get; set; }
}
public partial record CustomAttributeLinkConfiguration : CustomConfigurationBase {
	public bool? OneToOne { get; set; }
	public string EntityTypeTo { get; set; } = null!;
	public string? ObjectTypeIdTo { get; set; }
}
public partial record Action {
	public string? Id { get; init; }
	public string AutomationId { get; set; } = null!;
}
public partial record Automation {
	public string Id { get; init; } = null!;
	public string Name { get; set; } = null!;
	public string? Description { get; set; }
	public string? CreatedAt { get; set; }
	public string? CreatedBy { get; set; }
	public bool? Enabled { get; set; }
	public Action[]? Actions { get; set; }
	public Trigger[]? Triggers { get; set; }
}
public partial record FileComponent : Component {
}
public partial record CustomAttributeGroup {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public CustomAttributeConfiguration[]? CustomAttributeConfigurations { get; set; }
}
public partial record Recipient {
	public string NoteId { get; init; } = null!;
	public string ResourceId { get; init; } = null!;
	public string? TextMentioned { get; set; }
}
public partial record AssetType {
	public string Id { get; init; } = null!;
	public string Name { get; set; } = null!;
	public string Short { get; set; } = null!;
	public string? Component { get; set; }
	public Asset[]? Assets { get; set; }
}
public partial record Note {
	public string Id { get; init; } = null!;
	public string? ParentId { get; set; }
	public string? ParentType { get; set; }
	public string? Content { get; set; }
	public string? Date { get; set; }
	public string? ThreadActivity { get; set; }
	public string UserId { get; set; } = null!;
	public string? InReplyToId { get; set; }
	public string? CategoryId { get; set; }
	public bool? IsTodo { get; set; }
	public string? CompletedById { get; set; }
	public string? ProjectId { get; set; }
	public string? CompletedAt { get; set; }
	public Metadata[]? Metadata { get; set; }
	public Note[]? Replies { get; set; }
	public NoteComponent[]? NoteComponents { get; set; }
	public NoteLabelLink[]? NoteLabelLinks { get; set; }
	public Recipient[]? Recipients { get; set; }
	public int? FrameNumber { get; set; }
}
public partial record Location {
	public string Name { get; set; } = null!;
	public string? Label { get; set; }
	public string? Description { get; set; }
	public string Id { get; init; } = null!;
	public ComponentLocation[]? LocationComponents { get; set; }
}
public partial record TaskTypeSchemaType {
	public string TaskTypeSchemaId { get; init; } = null!;
	public string TypeId { get; init; } = null!;
}
public partial record State {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public string? Short { get; set; }
}
public partial record ProjectSchemaObjectType {
	public string ObjectTypeId { get; init; } = null!;
	public string ProjectSchemaId { get; init; } = null!;
}
public partial record AssetVersionStatusRuleGroup : StatusRuleGroup {
}
public partial record Metadata {
	public string ParentId { get; init; } = null!;
	public string ParentType { get; set; } = null!;
	public string Key { get; init; } = null!;
	public string Value { get; set; } = null!;
}
public partial record StatusChange {
	public string Id { get; init; } = null!;
	public string? ParentId { get; set; }
	public string? ParentType { get; set; }
	public string? Date { get; set; }
	public string? StatusId { get; set; }
	public string? FromStatusId { get; set; }
	public string? UserId { get; set; }
}
public partial record Schema {
	public string Id { get; init; } = null!;
	public string ProjectSchemaId { get; set; } = null!;
	public string TypeId { get; set; } = null!;
	public string? ObjectTypeId { get; set; }
	public SchemaStatus[]? Statuses { get; set; }
	public SchemaType[]? Types { get; set; }
}
public partial record List {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public bool IsOpen { get; set; }
	public string CategoryId { get; set; } = null!;
	public string? Date { get; set; }
	public string? UserId { get; set; }
	public string ProjectId { get; set; } = null!;
	public string? SystemType { get; set; }
	public ListCustomAttributeValue[]? CustomAttributes { get; set; }
	public CustomAttributeLink[]? CustomAttributeLinks { get; set; }
	public CustomAttributeLinkFrom[]? CustomAttributeLinksFrom { get; set; }
}
public partial record Group : Resource {
	public string Name { get; set; } = null!;
	public bool Local { get; set; }
	public string? ParentId { get; set; }
	public Group[]? Children { get; set; }
	public string? Link { get; set; }
	public Membership[]? Memberships { get; set; }
	public Metadata[]? Metadata { get; set; }
	public CustomAttributeLink[]? CustomAttributeLinks { get; set; }
	public CustomAttributeLinkFrom[]? CustomAttributeLinksFrom { get; set; }
}
public partial record CustomAttributeConfiguration : CustomConfigurationBase, IFtrackEntity
{
	public string EntityType { get; set; }
	public FtrackPrimaryKey[] GetPrimaryKeys()
	{
		throw new NotImplementedException();
	}
	public JsonElement? Default { get; set; }
	public bool? IsHierarchical { get; set; }
	public string? TypeId { get; set; }
	public CustomAttributeValue[]? Values { get; set; }
}
public partial record UserTaskTypeLink {
	public string UserId { get; init; } = null!;
	public string TypeId { get; init; } = null!;
}
public partial record EntitySetting {
	public string ParentId { get; init; } = null!;
	public string ParentType { get; set; } = null!;
	public string Group { get; init; } = null!;
	public string Name { get; init; } = null!;
	public string Value { get; set; } = null!;
}
public partial record Disk {
	public string Id { get; init; } = null!;
	public string Name { get; set; } = null!;
	public string? Unix { get; set; }
	public string? Windows { get; set; }
	public Project[]? Projects { get; set; }
}
public partial record UserView {
	public string Id { get; init; } = null!;
	public string? Name { get; set; }
	public bool? Global { get; set; }
	public string? UserId { get; set; }
	public Resource[]? SharedWith { get; set; }
}
public partial record Scope {
	public string Name { get; set; } = null!;
	public string Id { get; init; } = null!;
}
public partial record ContextCustomAttributeValue {
	public string ConfigurationId { get; init; } = null!;
	public JsonElement? Value { get; set; }
	public string EntityId { get; init; } = null!;
	public string? Key { get; set; }
}
public partial record AssetVersionCustomAttributeValue {
	public string ConfigurationId { get; init; } = null!;
	public JsonElement? Value { get; set; }
	public string EntityId { get; init; } = null!;
	public string? Key { get; set; }
}
public partial record ListCustomAttributeValue {
	public string ConfigurationId { get; init; } = null!;
	public JsonElement? Value { get; set; }
	public string EntityId { get; init; } = null!;
	public string? Key { get; set; }
}
public partial record ListObjectCustomAttributeValue {
	public string ConfigurationId { get; init; } = null!;
	public JsonElement? Value { get; set; }
	public string EntityId { get; init; } = null!;
	public string? Key { get; set; }
}
public partial record UserCustomAttributeValue {
	public string ConfigurationId { get; init; } = null!;
	public JsonElement? Value { get; set; }
	public string EntityId { get; init; } = null!;
	public string? Key { get; set; }
}
public partial record AssetCustomAttributeValue {
	public string ConfigurationId { get; init; } = null!;
	public JsonElement? Value { get; set; }
	public string EntityId { get; init; } = null!;
	public string? Key { get; set; }
}
public partial record ContextCustomAttributeLink : CustomAttributeLink {
}
public partial record ContextCustomAttributeLinkFrom : CustomAttributeLinkFrom {
}
public partial record AssetVersionCustomAttributeLink : CustomAttributeLink {
}
public partial record AssetVersionCustomAttributeLinkFrom : CustomAttributeLinkFrom {
}
public partial record ListCustomAttributeLink : CustomAttributeLink {
}
public partial record ListCustomAttributeLinkFrom : CustomAttributeLinkFrom {
}
public partial record UserCustomAttributeLink : CustomAttributeLink {
}
public partial record UserCustomAttributeLinkFrom : CustomAttributeLinkFrom {
}
public partial record GroupCustomAttributeLink : CustomAttributeLink {
}
public partial record GroupCustomAttributeLinkFrom : CustomAttributeLinkFrom {
}
public partial record AssetCustomAttributeLink : CustomAttributeLink {
}
public partial record AssetCustomAttributeLinkFrom : CustomAttributeLinkFrom {
}
public partial record ComponentCustomAttributeLink : CustomAttributeLink {
}
public partial record ComponentCustomAttributeLinkFrom : CustomAttributeLinkFrom {
}
